console.log("Branch 1");
console.log("not commiting");
console.log("test 1");
console.log("test 2");
console.log("test 2.2");
console.log("test 3");
console.log("commit 2");
console.log("commit 3");
console.log("commit 4");
